### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by YanzuSCrap** [Takaso/Replit-Discord-Token-Scraper#1]
Do you have discord for help ?

Traceback (most recent call last):
  File "/home/yanzu/Bureau/Replit-Discord-Token-Scraper/main.py", line 324, in <module>
    ultimate = Ultimate(); __import__("os").system("cls" if __import__("os").name == "nt" else "clear");
  File "/home/yanzu/Bureau/Replit-Discord-Token-Scraper/main.py", line 60, in __init__
    self.driver = webdriver.Chrome(options=opt_);
  File "/home/yanzu/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/yanzu/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "/home/yanzu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/yanzu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/yanzu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/yanzu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 117
Current browser version is 114.0.5735.198
Stacktrace:
#0 0x55873d7fc353 <unknown>
#1 0x55873d4d83f7 <unknown>
#2 0x55873d5101db <unknown>
#3 0x55873d50ad71 <unknown>
#4 0x55873d50783c <unknown>
#5 0x55873d54a276 <unknown>
#6 0x55873d540f93 <unknown>
#7 0x55873d5139fb <unknown>
#8 0x55873d5147ee <unknown>
#9 0x55873d7c1c38 <unknown>
#10 0x55873d7c5b60 <unknown>
#11 0x55873d7cfffc <unknown>
#12 0x55873d7c6768 <unknown>
#13 0x55873d793f4f <unknown>
#14 0x55873d7ea9a8 <unknown>
#15 0x55873d7eab79 <unknown>
#16 0x55873d7fb4e3 <unknown>
#17 0x7f0222894b43 <unknown>

**Comment by Takaso** [comment]
Update your chrome driver:
`pip uninstall chromedriver-binary`
then
`pip install chromedriver-binary`
